---
title: "Title"
subtitle: "Next Generation Sequencing 2025/2026"
author: "Cengiz Can Guner and Matija Zizek"
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    toc: true
    fig_height: 6
    number_sections: true
  html_document: 
    toc: true
editor_options: 
  markdown: 
    wrap: 80
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage 

# Setting The Environment

```{r, message=FALSE, warning=FALSE}
# ============================================================
# Install and Call Required NameSpaces
# ============================================================

# Install BioConductor package if not installed
if (!require("BiocManager", quietly = TRUE)) 
  install.packages("BiocManager")

# Package Lists
cran_pkgs <- c("tidyverse", "corrplot", "ggfortify")
bioc_pkgs <- c("edgeR", "EDASeq", "limma")

# Check, Install, and Call NameSpaces using CRAN
for (pkg in cran_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
    library(pkg, character.only = TRUE)
  } else {
    library(pkg, character.only = TRUE)
  }
}

# Check, Install, and Call NameSpaces using BioConductor
for (pkg in bioc_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    BiocManager::install(pkg)
    library(pkg, character.only = TRUE)
  } else {
    library(pkg, character.only = TRUE)
  }
}
```
\newpage

# Explarotary Analysis

```{r}
# ============================================================
# Load the Dataser from rds file
# ============================================================
rse <- readRDS("./opt/omicsdata/datasets/SRP029880.rds")
rse

# Inspect row and column names of the data
message("Row names: ", paste(rownames(rse)[1:3], collapse = ", "),
        "\nColumn names: ", paste(colnames(rse)[1:5], collapse = ", "))
```

The given dataset contains `r dim(rse)[1]` genes across `r dim(rse)[2]` samples.  

The column names represent sample names and the row names represent gene IDs.

# Normalization

# Differential Expression Analysis

# Gene Enrichment Analysis